"""initial schema: nine core entities

Revision ID: c776e466d326
Revises: 
Create Date: 2026-09-23 17:47:58.601748+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c776e466d326'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the nine entities of Architecture §14.1.

    Autogenerated, then adjusted twice by hand:
      * `astext_type=Text()` -> `sa.Text()`; Alembic renders JSONB with a bare
        `Text()` it never imports, which is a NameError at upgrade time.
      * `downgrade()` drops the eight enum types; `op.drop_table` leaves
        Postgres ENUM types behind, so a downgrade/upgrade cycle would fail
        with "type already exists" (FR-DEP-008 relies on that cycle working).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('source', sa.Enum('BUILT', 'ACQUIRED', name='capability_source'), nullable=False),
    sa.Column('status', sa.Enum('BUILDING', 'VERIFIED', 'FAILED', name='capability_status'), nullable=False),
    sa.Column('verification_score', sa.Float(), nullable=True),
    sa.Column('implementation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('capability_id'),
    sa.UniqueConstraint('name', 'version', name='uq_capabilities_name_version')
    )
    op.create_index(op.f('ix_capabilities_name'), 'capabilities', ['name'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('agents',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('framework', sa.Enum('python', 'rest', 'langchain', 'crewai', name='agent_framework'), nullable=False),
    sa.Column('endpoint', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='agent_status'), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_index(op.f('ix_agents_user_id'), 'agents', ['user_id'], unique=False)
    op.create_table('workflows',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='workflow_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    op.create_index(op.f('ix_workflows_user_id'), 'workflows', ['user_id'], unique=False)
    op.create_table('agent_capabilities',
    sa.Column('agent_capability_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('granted_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.capability_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_capability_id'),
    sa.UniqueConstraint('agent_id', 'capability_id', name='uq_agent_capabilities_agent_capability')
    )
    op.create_index(op.f('ix_agent_capabilities_agent_id'), 'agent_capabilities', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_capabilities_capability_id'), 'agent_capabilities', ['capability_id'], unique=False)
    op.create_table('executions',
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'SUCCEEDED', 'FAILED', name='execution_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_executions_user_id'), 'executions', ['user_id'], unique=False)
    op.create_index(op.f('ix_executions_workflow_id'), 'executions', ['workflow_id'], unique=False)
    op.create_table('workflow_agents',
    sa.Column('workflow_agent_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workflow_agent_id'),
    sa.UniqueConstraint('workflow_id', 'step_order', name='uq_workflow_agents_workflow_step_order')
    )
    op.create_index(op.f('ix_workflow_agents_agent_id'), 'workflow_agents', ['agent_id'], unique=False)
    op.create_index(op.f('ix_workflow_agents_workflow_id'), 'workflow_agents', ['workflow_id'], unique=False)
    op.create_table('execution_steps',
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'PAUSED', name='step_status'), nullable=False),
    sa.Column('recovery_stage', sa.Enum('NONE', 'DIAGNOSING', 'SEARCHING', 'BUILDING', 'SANDBOXING', 'TESTING', 'VERIFYING', 'REGISTERED', name='recovery_stage'), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.execution_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id')
    )
    op.create_index(op.f('ix_execution_steps_agent_id'), 'execution_steps', ['agent_id'], unique=False)
    op.create_index(op.f('ix_execution_steps_execution_id'), 'execution_steps', ['execution_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('checkpoint_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['execution_steps.step_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    op.create_index(op.f('ix_checkpoints_step_id'), 'checkpoints', ['step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkpoints_step_id'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('ix_execution_steps_execution_id'), table_name='execution_steps')
    op.drop_index(op.f('ix_execution_steps_agent_id'), table_name='execution_steps')
    op.drop_table('execution_steps')
    op.drop_index(op.f('ix_workflow_agents_workflow_id'), table_name='workflow_agents')
    op.drop_index(op.f('ix_workflow_agents_agent_id'), table_name='workflow_agents')
    op.drop_table('workflow_agents')
    op.drop_index(op.f('ix_executions_workflow_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_user_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_agent_capabilities_capability_id'), table_name='agent_capabilities')
    op.drop_index(op.f('ix_agent_capabilities_agent_id'), table_name='agent_capabilities')
    op.drop_table('agent_capabilities')
    op.drop_index(op.f('ix_workflows_user_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_agents_user_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('users')
    op.drop_index(op.f('ix_capabilities_name'), table_name='capabilities')
    op.drop_table('capabilities')
    # ### end Alembic commands ###

    # op.drop_table does not remove the Postgres ENUM types that create_table
    # implicitly created, so drop them explicitly to keep downgrade reversible.
    for enum_name in (
        'step_status',
        'recovery_stage',
        'execution_status',
        'agent_status',
        'workflow_status',
        'capability_status',
        'agent_framework',
        'capability_source',
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS {enum_name}'))
